#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
EVIDENCE = ROOT / "experiments" / "evidence"
SCREENSHOTS = DOCS / "screenshots"
RUNBOOKS = DOCS / "runbooks"

DOCS.mkdir(parents=True, exist_ok=True)
RUNBOOKS.mkdir(parents=True, exist_ok=True)

def human(value: str) -> str:
    return value.replace("-", " ").replace("_", " ").title()

lines = [
    "# Evidence Index",
    "",
    "This index provides a navigable inventory of technical proof generated by the Kubernetes Reliability Lab.",
    "",
    "## Curated Screenshots",
    "",
    "| Screenshot | Evidence |",
    "|---|---|",
]

screenshots = []
if SCREENSHOTS.exists():
    screenshots = sorted(
        p for p in SCREENSHOTS.iterdir()
        if p.is_file() and p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".svg"}
    )

for p in screenshots:
    lines.append(f"| [{p.name}](screenshots/{p.name}) | {human(p.stem)} |")

if not screenshots:
    lines.append("| None yet | Add final curated screenshots before completion |")

lines += ["", "## Raw Evidence", ""]

groups = {}
if EVIDENCE.exists():
    for p in sorted(EVIDENCE.rglob("*")):
        if not p.is_file() or p.name in {".DS_Store", ".gitkeep"}:
            continue
        rel = p.relative_to(EVIDENCE)
        category = rel.parts[0] if len(rel.parts) > 1 else "general"
        groups.setdefault(category, []).append(p)

for category in sorted(groups):
    lines += [
        f"### {human(category)}",
        "",
        "| File | Type |",
        "|---|---|",
    ]
    for p in groups[category]:
        rel = p.relative_to(EVIDENCE)
        link = "../experiments/evidence/" + rel.as_posix()
        kind = p.suffix.lstrip(".").upper() or "FILE"
        lines.append(f"| [{rel.as_posix()}]({link}) | {kind} |")
    lines.append("")

(DOCS / "evidence-index.md").write_text(
    "\n".join(lines).rstrip() + "\n",
    encoding="utf-8"
)

runbooks = sorted(
    p for p in DOCS.rglob("*.md")
    if "runbook" in p.name.lower() and p.name != "index.md"
)

lines = [
    "# Runbook Index",
    "",
    "Operational procedures for diagnosing and recovering the Kubernetes Reliability Lab.",
    "",
]

for p in runbooks:
    title = p.stem.replace("-", " ").title()
    try:
        for line in p.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
    except OSError:
        pass

    link = "../" + p.relative_to(DOCS).as_posix()
    lines.append(f"- [{title}]({link})")

if not runbooks:
    lines.append("- No runbooks discovered.")

(RUNBOOKS / "index.md").write_text(
    "\n".join(lines).rstrip() + "\n",
    encoding="utf-8"
)

print("PASS: Generated docs/evidence-index.md")
print("PASS: Generated docs/runbooks/index.md")
print(f"Indexed {len(screenshots)} screenshots")
print(f"Indexed {len(runbooks)} runbooks")
