apiVersion: v1
kind: Pod
metadata:
  name: latest-tag-test
  namespace: reliability-lab
  labels:
    app.kubernetes.io/name: latest-tag-test
    app.kubernetes.io/part-of: kubernetes-reliability-lab
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
