apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: multi-service-app
    app.kubernetes.io/part-of: kubernetes-reliability-lab
spec:
  project: reliability-platform
  source:
    repoURL: https://github.com/sammyutere/kubernetes-reliability-lab.git
    targetRevision: main
    path: helm/multi-service-app
    helm:
      releaseName: multi-service-app
      valueFiles:
        - values-eks.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reliability-lab
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
