{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reliability-app.fullname" . }}-pdb
  labels:
    {{- include "reliability-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: availability
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "reliability-app.selectorLabels" . | nindent 6 }}
{{- end }}
