apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reliability-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: GitOps project for the Kubernetes Reliability Lab

  sourceRepos:
    - https://github.com/sammyutere/kubernetes-reliability-lab.git

  destinations:
    - namespace: reliability-lab
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
