{{- if .Values.serviceMonitor.enabled }}
{{- range $name, $svc := .Values.services }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}
  labels:
    release: monitoring
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: multi-service-reliability-lab
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
{{- end }}
{{- end }}
