apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reliability-app-hpa
  namespace: reliability-lab
  labels:
    app.kubernetes.io/name: reliability-app
    app.kubernetes.io/part-of: kubernetes-reliability-lab
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/managed-by: kubectl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reliability-app
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
